export enum colors {
  PRIMARY_COLOR_MAIN = "#EE7E23",
  SECONDARY_COLOR_MAIN = "#31354C",
  SECONDARY_COLOR_LITE = "#5A5D70",
  DIVIDER_LINE_COLOR = "#EEEEEE",
  WHITE_COLOR = "#FFFFFF",
  CONTACT_BG_COLOR = "#EDF1F6",
  FONT_COLOT_LITE = "#838694",
  FOOTER_LINK_TITLE = "#838694",
  BG_COLOR = "#F5F5F5",
  USER_INFO_BGCOLOR = "#E0F7FA",
  USER_TXT_COLOR = "#00838F",
}
