import React from "react";
import { Button, Box } from "@material-ui/core";
import { useRouter } from "next/router";
import _ from "lodash";

const LeadViewTable = ({ data, onClick }) => {
  const router = useRouter();
  return (
    <div>
      <div className="orderTable">
        <table className="table">
          <tr>
            <td className="cellSelect">Lead Id:</td>
            <td>{data.leadId}</td>
            <td className="cellSelect">Lead Date:</td>
            <td>{data.leadDate}</td>
          </tr>

          <tr>
            <td className="cellSelect">Studio:</td>
            <td>{data.studioId}</td>
            <td className="cellSelect">Generated By:</td>
            <td>{data.generatedBy}</td>
          </tr>
          <tr>
            <td className="cellSelect">Name:</td>
            <td>{data.name}</td>
            <td className="cellSelect">Phone No:</td>
            <td>{data.phone}</td>
          </tr>
          <tr>
            <td className="cellSelect">Persona:</td>
            <td>{data.persona}</td>
            <td className="cellSelect">City:</td>
            <td>{data.cityName}</td>
          </tr>

          <tr>
            <td className="cellSelect">Source:</td>
            <td>{data.source}</td>
            <td className="cellSelect">Credited To:</td>
            <td>{data.creditTo}</td>
          </tr>

          <tr>
            <td className="cellSelect">Exp Closure Date:</td>
            <td>{data.expClosureDate}</td>
            <td className="cellSelect">Event Date:</td>
            <td>{data.eventDate}</td>
          </tr>

          <tr>
            <td className="cellSelect">Follow Up Date:</td>
            <td>{data.followUpDate}</td>
            <td className="cellSelect">Estimated Value:</td>
            <td>{data.estimatedValue}</td>
          </tr>

          <tr>
            <td className="cellSelect">Lead Rating:</td>
            <td>{data.rating}</td>
            <td className="cellSelect">Remarks:</td>
            <td>{data.remarks}</td>
          </tr>
          <tr>
            <td className="cellSelect">Status:</td>
            <td>{data.status}</td>
            <td className="cellSelect">Reason</td>
            <td>{data._status.note}</td>
          </tr>
        </table>
      </div>

      <Box display="flex" alignItems="center">
        <Box mr={1}>
          <Button
            color="secondary"
            onClick={() => {
              router.push(`/leads/addLeads?leadId=${data.id}`);
            }}
          >
            Edit
          </Button>
        </Box>
      </Box>
    </div>
  );
};

export default LeadViewTable;
